spring:
  main:
    banner-mode: off
    log-startup-info: false
    lazy-initialization: true

  sql:
    init:
      continue-on-error: true

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/self
    username: postgres
    password: 19982011
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        default_schema: gis # for localhost only
        "[format_sql]": true
        "[generate_statistics]": true
server:
  port: ${PORT:8080}

